backend:
  name: git-gateway
  accept_roles:
    - admin

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: page
    label: Page
    folder: src/markdown/pages
    create: true
    fields:
      - label: Title
        name: title
        widget: string
        tagname: h1
        required: true
      - label: Template
        name: template
        widget: string
        required: false
      - label: Image
        name: image
        widget: image
        required: false
      - label: Cloudinary Image
        name: cloudinaryImage
        widget: cloudinary
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false