[Settings]
	ID = "zygote-cart"

[build]
	command = "sed -i 's/E_API_KEY_PLACEHOLDER/${ESCA_API_KEY}/g; s/E_API_CONTEXT_PLACEHOLDER/${ESCA_API_SITE}/g; s/AMAZON_API_KEY_PLACEHOLDER/${X_API_Key}/g' netlify.toml && yarn build && yarn build:gatsby"
	publish = "public"
	functions = "dist-functions"

[[redirects]]
	from = "/admin"
	to = "/admin/"

## COMMENT: This rule redirects to an external api
[[redirects]]
  from = "/api/info"
  to = "https://inventory-test.escsportsapi.com/load"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  [redirects.headers]
    Content-Type = "application/json"
		ESC-API-Key = "E_API_KEY_PLACEHOLDER"
		ESC-API-Context = "E_API_CONTEXT_PLACEHOLDER"
